### ISSUE TITLE
Getting error on instantiation of emfit custom component

### ISSUE THREAD

**Issue by harperreed** [jxlarrea/ha-emfitqs#1]
`2019-09-08 18:33:52 ERROR (MainThread) [homeassistant.setup] Setup failed for emfitqs: No setup function defined.`

It works - but the "setup" fails

**Comment by jxlarrea** [comment]
So the "setup" fails but the component works properly? I tried uninstalling and reinstalling it and never got that message. Which HA and HACS versions are you running?

**Comment by harperreed** [comment]
Home Assistant: 0.98.4
Not using HACS. Manual install.

**Comment by jxlarrea** [comment]
Thanks. Does the component work at all even though you get that message?

**Comment by harperreed** [comment]
Yep. It works great (i think - i haven't slept yet..)

![image](https://user-images.githubusercontent.com/18504/64502585-8a5b3b80-d28c-11e9-8ae3-089b6a7f99c6.png)

**Comment by jxlarrea** [comment]
Well, it is certainly working. I attempted to reproduce the error message by manually installing the component but it never showed up in my logs. I will close the issue for now.
