### ISSUE TITLE
Integration not loading, mutliple errors

### ISSUE THREAD

**Issue by docmishra** [jxlarrea/ha-emfitqs#2]
Hey there, 

Thanks for your work on this integration! I just got my emfit and have been really looking forward to getting it integrated into hassio. I just gave your custom component a go, but seem to be having trouble. 

I'm running Home Assistant 2021.1.4 using the docker script on an old ubuntu laptop.

Got a bunch of errors in the log: 

`Logger: homeassistant.components.binary_sensor
Source: components/binary_sensor/__init__.py:172
Integration: Binary Sensor (documentation, issues)
First occurred: 14:47:10 (1 occurrences)
Last logged: 14:47:10
BinarySensorDevice is deprecated, modify EmfitQSBinarySensor to extend BinarySensorEntity`

`Logger: homeassistant.setup
Source: setup.py:138
First occurred: 14:47:10 (1 occurrences)
Last logged: 14:47:10
Setup failed for emfitqs: No setup function defined`

`Logger: custom_components.emfitqs.binary_sensor
Source: custom_components/emfitqs/binary_sensor.py:81
Integration: emfitqs (documentation)
First occurred: 14:47:14 (1 occurrences)
Last logged: 14:47:14
Error ocurred: ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.1.3', port=80): Max retries exceeded with url: /dvmstatus.htm (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdeceacbf70>: Failed to establish a new connection: [Errno 113] Host is unreachable'))"))`

`Logger: custom_components.emfitqs.binary_sensor
Source: custom_components/emfitqs/binary_sensor.py:51
Integration: emfitqs (documentation)
First occurred: 14:47:14 (1 occurrences)
Last logged: 14:47:14
Error ocurred: KeyError('ser')`

Any ideas/suggestions would be greatly appreciated!! Would be great to get this going!

**Comment by jxlarrea** [comment]
Hi, the only relevant error there is the one with `ConnectionError`. That means that it couldn't connect to the EmfitQS device. Are you sure that 192.168.1.3 is the IP of your Emfit?

You can test it by trying to connect to it via a web browser: `http://192.168.1.3/dvmstatus.htm` If it doesn't work, that means that you are using the wrong IP address.

**Comment by docmishra** [comment]
Hey there! 
Thanks for the quick reply, much appreciated!! So it seems that the emfit wasn't running the HTTP server for some reason, turned it on and off and now it's working in the browser too at http://192.168.1.3/dvmstatus.htm , its definitely the right IP. 
Unfortunately, it is still giving me errors and not starting. 


`Logger: homeassistant.setup
Source: setup.py:138
First occurred: 7:13:29 (1 occurrences)
Last logged: 7:13:29
Setup failed for emfitqs: No setup function defined.`

`Logger: homeassistant.components.binary_sensor
Source: components/binary_sensor/__init__.py:172
Integration: Binary Sensor (documentation, issues)
First occurred: 9:00:51 (1 occurrences)
Last logged: 9:00:51
BinarySensorDevice is deprecated, modify EmfitQSBinarySensor to extend BinarySensorEntity`

Thanks for your help with this!!

**Comment by jxlarrea** [comment]
Those are just warnings, not errors. Are you sure that you don't see in developer tools any EmfitQS entities such as `binary_sensor.emfitqs_xxxxxx_bed_presence` ?

**Comment by docmishra** [comment]
Yep your right! Glad to say its working now! Thanks for all your help and sorry for wasting your time!! I think it mus thave just been the emfit not running the server for some reason initially.

Thanks again!
