### ISSUE TITLE
Have you seen the EMFIT API?

### ISSUE THREAD

**Issue by mrbob1234** [jxlarrea/ha-emfitqs#3]
Hey there! 

Hope you are keeping well. Thankyou for your work on this component, it has been working perfectly! 

I just came across this : https://github.com/samuelmr/emfit-qs and was wondering if you had seen it? I've had some success using postman to login using get https://qs-api.emfit.com/api/v1/login?username=[]&password=[] to get my token then get https://qs-api.emfit.com/api/v1/presence/device_id/latest? returns a lot of information about the latest sleep scores and trends etc. It would be amazing to be able to pull in things like the sleep score and HRV readings. I'm only a novice with these things, considering using node red to help me get some of the data into Hassio. Any chance you would be interested in adding/using this in the component?

**Comment by jxlarrea** [comment]
Not planning on directly interfacing with Emfit's API. This integration focuses on interfacing with the device locally.
