### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by Sleepy81** [jxlarrea/ha-emfitqs#4]
I have HA core-2021.12.8, supervisor-2021.12.2 and Home Assistant OS 7.1.

After installing via HACS, i then input the required info in the configuration.yaml.

I however get the following error messages during a configuration check:

Integration error: emfitqs - Integration 'emfitqs' not found.
Platform error sensor.emfitqs - Integration 'emfitqs' not found.
Platform error binary_sensor.emfitqs - Integration 'emfitqs' not found.

Looks like its installed correctly in HACS, Any ideas? Maybe a HA update broke this integration?

**Comment by Sleepy81** [comment]
Disregard. Found it. Missing Version key in manifest.json.
Add "version": "2.2", after "name": in the file and this integration loads without errors.

**Comment by jxlarrea** [comment]
Hey thanks for that. I will add the missing  key right now.

**Comment by jxlarrea** [comment]
That is strange. The file manifest.json already includes the version key. Perhaps HACS is pulling an older version? Not sure.

**Comment by Sleepy81** [comment]
HACS downloaded versjon 2.2. But, I just recently edited the manifest.json file here on GitHub and added the version key. First time adding to a project on Github for me, but I assumed that would create some sort of approval in your end, to make the change "official.". So might be the change I made you see on github now? :)

**Comment by Sleepy81** [comment]
Btw: this is the manifest file HACs downloaded for me:

  "domain": "emfitqs",
  "name": "Emfit QS Sleep Tracker",
  "documentation": "https://github.com/jxlarrea/ha-emfitqs",
  "dependencies": [],
  "codeowners": [ "@jxlarrea" ],
  "requirements": []


Changed it to this, and then it worked:
  "domain": "emfitqs",
  "name": "Emfit QS Sleep Tracker",
  "version": "2.2",
  "documentation": "https://github.com/jxlarrea/ha-emfitqs",
  "dependencies": [],
  "codeowners": [ "@jxlarrea" ],
  "requirements": []

**Comment by jxlarrea** [comment]
Strange. I actually added that key about 7 months ago when it stopped working for me too. Check the edit history of the file. 

https://github.com/jxlarrea/ha-emfitqs/commit/5a9f22519191137a1c50f4a071ca42ddc6661077#diff-1735674960d274353dcbdf63a6f13c6687d4fa569e7f963b01ea3bc7aa95909a
