### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by seannymurrs** [jxlarrea/ha-emfitqs#8]
How would I go about adding a unique ID for the various entities from my Emit QS? I'd like to do so in order to be able to assign the entities to different areas. Without a unique ID, it won't let me do much of anything.

**Comment by ukd1** [comment]
Not that I've got this installed yet, but the docs say [In Home Assistant, the component sensor names include the device serial number, for example `binary_sensor.emfitqs_012345_bed_presence` and `sensor.emfitqs_012345_heart_rate` ...](https://github.com/jxlarrea/ha-emfitqs/blob/aa75a411082433fdad7bf5c8ce81e9f4491b12dd/README.md?plain=1#L70) - so I you have more than one device, they should just appear distinctly after you set them up.

**Comment by jxlarrea** [comment]
> How would I go about adding a unique ID for the various entities from my Emit QS? I'd like to do so in order to be able to assign the entities to different areas. Without a unique ID, it won't let me do much of anything.

All sensors include the serial number of each device making them unique.
